### ISSUE TITLE
请问数据集可以获取吗？

### ISSUE THREAD

**Issue by Kevin9780** [chungdz/GERLMind#1]

**Comment by chungdz** [comment]
[数据集](https://msnews.github.io/)

读论文复原代码，非官方

**Comment by Kevin9780** [comment]
非常感谢！

**Comment by HonQing-Xu** [comment]
> [数据集](https://msnews.github.io/)
> 
> 读论文复原代码，非官方

请问在MIND数据集上复现出论文的效果了吗？
